USE SALES10M;

SELECT * FROM SALES;

-- Contagem de orders
SELECT COUNT(DISTINCT SALES.ORDERID)
FROM SALES;

SELECT SALES.ORDERID, COUNT(SALES.ORDERID) AS "Count_Orders"
FROM SALES
GROUP BY SALES.ORDERID
ORDER BY Count_Orders DESC;

SELECT *
FROM SALES
WHERE SALES.ORDERID = '1759588';


-- Período de vendas registrado (orders)
SELECT DISTINCT(SALES.DATE_)
FROM SALES
ORDER BY SALES.DATE_;


-- Usuários distintos
SELECT COUNT(DISTINCT SALES.USERID)
FROM SALES;

SELECT SALES.USERID, SALES.USERNAME_
FROM SALES;


-- Usuário que mais gastou (faturamento)
SELECT SALES.USERID, SUM(SALES.TOTALPRICE) AS "Total"
FROM SALES
GROUP BY SALES.USERID
ORDER BY Total DESC;

SELECT *
FROM SALES
WHERE USERID = '2896';

-- Top3 produtos mais saída usuário top1
SELECT SALES.ITEMNAME, SUM(SALES.AMOUNT) AS "VENDAS_TOTAIS" 
FROM SALES
WHERE USERID = '2896'
GROUP BY SALES.ITEMNAME
ORDER BY VENDAS_TOTAIS DESC;


-- Top3 produtos maior faturamento
SELECT TOP 3 SALES.ITEMNAME, SUM(SALES.TOTALPRICE) AS "VENDAS_TOTAIS" 
FROM SALES
GROUP BY SALES.ITEMNAME
ORDER BY VENDAS_TOTAIS DESC;

-- Produtos com maiores descontos
SELECT SALES.ITEMNAME, SALES.UNITPRICE - SALES.PRICE AS "DESCONTO"
FROM SALES
ORDER BY DESCONTO DESC;


-- Qtde de unidades (produtos) vendidas
SELECT SALES.ITEMNAME, SUM(SALES.AMOUNT) AS "TOTAL_VENDAS"
FROM SALES
GROUP BY SALES.ITEMNAME
ORDER BY TOTAL_VENDAS DESC;

-- Ano que mais faturou
SELECT DATEPART(YEAR, SALES.DATE_) AS "YEAR", SUM(SALES.TOTALPRICE) AS "TOTAL_VENDA"
FROM SALES
GROUP BY DATEPART(YEAR, SALES.DATE_)
ORDER BY TOTAL_VENDA DESC;

-- Faturamento total período
SELECT SUM(SALES.TOTALPRICE) AS "FATURAMENTO_TOTAL"
FROM SALES;


-- Faturamento por brands
SELECT SALES.BRAND, SUM(SALES.TOTALPRICE) AS "TOTAL"
FROM SALES
GROUP BY SALES.BRAND
ORDER BY TOTAL DESC;

-- Faturamento por região
SELECT SALES.REGION, SUM(SALES.TOTALPRICE) AS "TOTAL"
FROM SALES
GROUP BY SALES.REGION
ORDER BY TOTAL DESC;

-- N° Orders na cidade de maior faturamento
SELECT COUNT(DISTINCT SALES.ORDERID)
FROM SALES
WHERE SALES.REGION = 'Marmara';